version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/plywoodInventory
    networks:
      - inventory-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - inventory-net

  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - inventory-net

networks:
  inventory-net:
    driver: bridge

volumes:
  mongo-data:
